### ISSUE TITLE
Incorrect generation count

### ISSUE THREAD

**Issue by AdarkTheCoder** [EgoMoose/Rbx_CustomFont#11]
When generating multiple font families, some are counted multiple times (as seen in example gif)

**Comment by EgoMoose** [comment]
Example gif?

**Comment by AdarkTheCoder** [comment]
On the wiki page for setting up your own fonts.

**Comment by EgoMoose** [comment]
Ahh it took me so long to see what you were talking about, but I finally see it! Alright I'll fix it!
