### ISSUE TITLE
Server Scripts for billboard GUIs

### ISSUE THREAD

**Issue by OldGoldie** [EgoMoose/Rbx_CustomFont#12]
When I use a server script this happens http://prntscr.com/brgn9m  I want to use it on BillboardGuis, and I want everyone to see it so local script wouldn't really work. It seems there is a random text stroke text that works fine. But the main text is stuck on the side of the GUI and at "5" with sometimes fine and sometimes messed up text stroke. I use "Replace"

**Comment by EgoMoose** [comment]
Sorry for late reply. I'll take a look into tonight ideally. Can you tell me the name of the font you used and ideally the link for it as well? It will help me in debugging.

**Comment by OldGoldie** [comment]
http://www.dafont.com/super-mario-256.font This is the font. I was able to get it to work with a remote event doinng font.Replace locally, but text stroke still messes up on the first text and when you move your camera.

**Comment by EgoMoose** [comment]
I unfortunately had to remove the text stroke feature as I found I was unable to get it to look good consistently with any font.
