### ISSUE TITLE
Spacing is off

### ISSUE THREAD

**Issue by Narrev** [EgoMoose/Rbx_CustomFont#14]
As you can see, the font just doesn't turn out as it should.
![font compare](https://cloud.githubusercontent.com/assets/15217173/17319797/e475b19a-5855-11e6-8163-03998dc0aa2a.png)

**Comment by EgoMoose** [comment]
Sorry for the late response. Cleaning up the code for the generator in this project is on my to-do list. I will look into this problem when I end up doing that.

**Comment by Narrev** [comment]
This one works really well:
https://www.roblox.com/FontLibrary-item?id=245048459

I modified it so I could keep a library like this:
```lua
local Fonts = {
	Roboto = {
		Regular = {
			[8]  = 470610229;
			[9]  = 470610317;
			[10] = 470610378;
			[11] = 470610465;
			[12] = 470610559;
			[14] = 470600299;
			[16] = 470610658;
			[18] = 470610816;
			[20] = 470610907;
			[22] = 470610946;
			[24] = 470610997;
			[26] = 470611043;
			[28] = 470611078;
			[36] = 470611132;
			[48] = 470611187;
			[72] = 470611246;
		};
		
		Bold = {
			-- Don't actually have id's for this yet
		};

		Italics = {
			-- 
		};
	};

	OtherFont = {}
};
```

On each of those files, the data necessary is kept in the description of the image. Also, that way you can do `Text.Bold = true` and it can switch to the proper version of the font.

**Comment by Narrev** [comment]
How long until you plan on reexamining this module?

**Comment by EgoMoose** [comment]
So sorry about that. I've had a lot of unexpected  stuff pop up in my life over the past month that I've been really busy with and because of it I've not been able to get as much done as I would have liked to. The good news is that school is starting for me this week (I don't live at home during school) and once I get settled I'll have more time to work on it.

So in short, sorry for the delay, but I'll be working on it hopefully by next weekend!

**Comment by Narrev** [comment]
Hey, thank you for your dedication. We all do this stuff for free, you know?

**Comment by Narrev** [comment]
Sorry for pestering you about this so much, but I would like to know when this can be expected to be fixed up. You said you hopefully can work on it this weekend, so is that still possible?

An interesting feature that I thought should be considered for implementation is tweening the type-prompt line. [Here is a video](https://www.youtube.com/watch?v=eDEVNcSArlc&t=189) displaying the feature I am referring to. I could work on this if you don't want to, but the generation code will need to be fixed first.
